### PR TITLE
Update `Collection` nomenclature to be more explicit

### PR DESCRIPTION
**Pull request by jakerockland**
This updates the nomenclature of `Collection` to use the more explicit nomenclature of `Contract` as there are often contracts that have multiple different collections/projects within them (e.g. Art Blocks, various partner platforms powered by the Art Blocks Engine, SuperRare, Foundation, etc.), and while I don't think it makes sense for this registry to be aware of the nuances of how various contracts handle the abstraction of "collection" or "project", I do think that the nomenclature used by the registry should be as explicit here as possible to avoid any opportunity for developer / user error due to confusion.

### CODE REVIEW

**Comment by jakerockland** [comment]
cc @ryley-o

**Comment by dmfxyz** [comment]
Contracts might have multiple collections, so maybe you only want to delegate for one? Could add say a `collectionId`, if it doesn't become too much of a hairball. Or perhaps calling contracts can use roles to identify collections. Both titles have confusing semantics imo.

**Comment by jakerockland** [comment]
> Contracts might have multiple collections, so maybe you only want to delegate for one? 

Yeah that's very fair, but isn't/wasn't the behavior as-implemented currently, so I think this PR at least updates the functionality to match the nomenclature.

> Could add say a `collectionId`, if it doesn't become too much of a hairball. Or perhaps calling contracts can use roles to identify collections. Both titles have confusing semantics imo.

That's definitely possible, but that does seem a bit hairball to me, though at a high-level concept wise this would definitely apply to our use-case at Art Blocks, where contracts do have multiple collections/projects within them. 

That said, I think with the primitives of `contract` (we probably wouldn't use this for our Art Blocks use case), `token` and `all`, clients have decent enough coverage area to work around things.

If we really think the collection-as-a-subset-of-a-contract is a widely used one, I'd suggest we go the Seaport approach of handling this via a Merkle-proof of a set of token IDs. 

That is, by having the four ACL groupings of `contract`, `token`, `tokens`*, and `all`, where tokens plural is captured by the combination of a contract address and a merkle proof for a set of associated token IDs. 

That said, that feels like it may be more complexity than it is worth?

**Comment by ryley-o** [comment]
I'm a big proponent of using `contract` nomenclature instead of `collection`! 
"collection" sometimes indicates "contract", but certainly not always (e.g. Art Blocks).

Adding a `tokens` option via Merkle proof schema is certainly possible. I think the main drawback might be that integrators would have to add the complexity of submitting Merkle proofs when checking for delegation. That would require a user to have some standard way of representing the off-chain list of tokens, which would probably be an off-chain csv or json file (thinking json because we would also need to know the contract)... things start to get more difficult for integrators when mixing off-chain and on-chain data 😅

**Comment by 0xfoobar** [comment]
Great discussion on how a contract can hold multiple sub-collections. Agree it would be interesting to look at merkle proofs for sub-contract level token groupings, but this introduces introducing offchain storage dependencies for the tree itself as mentioned above.

Good renaming in any case. I think the keyword `contract` might be a special Solidity reserved name, causing CI to fail. As soon as that's resolved @jakerockland looks good to merge

**Comment by ryley-o** [comment]
@jakerockland per https://docs.soliditylang.org/en/develop/style-guide.html#avoiding-naming-collisions,
recommend changing everything to `contract_` 👍

**Comment by jakerockland** [comment]
Apologies for the naming collision issue folks 😄 

Fixed that and associated tests 💜 

+++ to your thoughts above @0xfoobar and @ryley-o that the Merkle proof suggestion is likely something to be treated as out of scope.

**Review by rookmate — APPROVED** [review]

**Comment by 0xfoobar** [comment]
lgtm, ty!

**Pull request merged**
